[package]
name = "tch-geometric"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tch_geometric"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }
tch = { git = "https://github.com/EgorDm/tch-rs.git", features = ["torch_python"], default-features = false }