package:
  name: tch_geometric
  version: 0.1.0

source:
  path: ../..

requirements:
  build:
    - {{ compiler('c') }}  # [win]
    - conda-forge::rust==1.61.0

  host:
    - pip
    - python {{ environ.get('PYTHON_VERSION') }}
    - {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    - {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
    - conda-forge::toml==0.10.2
    - conda-forge::setuptools-rust==1.3.0

  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    - {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}

build:
  string: py{{ environ.get('PYTHON_VERSION').replace('.', '') }}_torch_{{ environ['TORCH_VERSION'] }}_{{ environ['CUDA_VERSION'] }}
  script: |
    export PYTHON_INCLUDE_DIRS=$(python -c "from sysconfig import get_paths as gp; print(gp()['include'])")
    export PYTHON_SITE_DIR=$(python -c "import site; print(site.getsitepackages()[0])")
    export LIBTORCH="$PYTHON_SITE_DIR/torch"
    export LD_LIBRARY_PATH="$PYTHON_SITE_DIR/torch/lib:$LD_LIBRARY_PATH"
    export LIBTORCH_CXX11_ABI="0"
    pip install .
  script_env:
    - FORCE_CUDA
    - TORCH_CUDA_ARCH_LIST
    - TORCH_CUDA_VERSION

test:
  imports:
    - tch_geometric

about:
  home: https://github.com/EgorDm/tch-geometric
  license: MIT
  summary: Pytorch Geometric extension library with additional graph sampling algorithms.