name: Release

on:
  push:
    branches:
      - ci
  workflow_dispatch:


jobs:
  wheel:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-18.04
#          - macos-10.15
#          - windows-2019
#        python-version: ['3.7', '3.9']
        python-version: ['3.9']
        torch-version: [1.11.0]
#        cuda-version: ['cpu', 'cu102', 'cu113', 'cu115']
        cuda-version: ['cpu']

    runs-on: ${{ matrix.os }}
    container:
#      image: pytorch/manylinux-cuda113
      image: pytorch/manylinux-cpu

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
#    - uses: actions-rs/toolchain@v1
#      if: ${{ matrix.os }} == 'macos-10.15'
#      with:
#        toolchain: stable
#        target: aarch64-apple-darwin
#        override: true
#
#
#    - name: Install CUDA ${{ matrix.cuda-version }}
#      if: ${{ matrix.cuda-version != 'cpu' }}
#      run: |
#        bash .github/workflows/cuda/${{ matrix.cuda-version }}-${{ runner.os }}.sh

    - name: Install PyTorch ${{ matrix.torch-version }}+${{ matrix.cuda-version }}
      run: |
        pip install numpy typing-extensions dataclasses
        pip install --no-index --no-cache-dir torch==${{ matrix.torch-version}} -f https://download.pytorch.org/whl/${{ matrix.cuda-version }}/torch_stable.html
        python -c "import torch; print('PyTorch:', torch.__version__)"
        python -c "import torch; print('CUDA:', torch.version.cuda)"
        export PY_SITE_DIR=$(python -c "import site; print(site.getsitepackages()[0])")
        echo "LIBTORCH=$PY_SITE_DIR/torch" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$PY_SITE_DIR/torch/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - uses: messense/maturin-action@v1
      with:
        container: off
        command: build
        args: --release -o dist
      env:
        LIBTORCH_CXX11_ABI: "0"
        LIBTORCH: ${{ env.LIBTORCH }}
        LD_LIBRARY_PATH: ${{ env.LD_LIBRARY_PATH }}
        TORCH_CUDA_VERSION: ${{ matrix.cuda-version }}
        VERSION_SUFFIX: ${{ matrix.cuda-version }}

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: messense/maturin-action@v1
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      with:
        container: off
        command: upload
        args: --repository-url https://test.pypi.org/legacy/ --skip-existing *

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: messense/maturin-action@v1
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      with:
        container: off
        command: upload
        args: --skip-existing *