name: Release

on:
  push:
    branches:
      - ci
  workflow_dispatch:


jobs:
  wheel:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-18.04
#          - macos-10.15
#          - windows-2019
#        python-version: ['3.7', '3.9']
        python-version: ['3.9']
        torch-version: [1.11.0]
#        cuda-version: ['cpu', 'cuda102', 'cuda113', 'cuda115']
        cuda-version: ['cpu']

    runs-on: ${{ matrix.os }}
    container:
#      image: pytorch/manylinux-cuda113
      image: pytorch/manylinux-cpu

    steps:
    - uses: actions/checkout@v2
    - name: Setup Env ${{ matrix.torch-version }}+${{ matrix.cuda-version }}
      run: bash .github/workflows/setup_env.sh
      env:
        TORCH_VERSION: ${{ matrix.torch-version }}
        CUDA_VERSION: ${{ matrix.cuda-version }}

    - name: Build wheel
      run: |
        pip install maturin
        maturin build --release -o dist
        ls -la dist
      env:
        LIBTORCH_CXX11_ABI: "0"
        VERSION_SUFFIX: ${{ matrix.cuda-version }}

    - name: Publish to PyPI Test
      run: |
        maturin upload --repository-url https://test.pypi.org/legacy/ --skip-existing dist/*
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      run: |
        maturin upload --skip-existing dist/*
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}